// <auto-generated />
using System;
using Gradus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gradus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GradusDbContext))]
    partial class GradusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gradus.Domain.Entities.HomologationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoordinatorNotes")
                        .HasColumnType("text")
                        .HasColumnName("coordinator_notes");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DocumentGeneratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("document_generated_at");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text")
                        .HasColumnName("document_url");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedByAzureOid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reviewed_by_azure_oid");

                    b.Property<string>("SourceProgramCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_program_code");

                    b.Property<string>("SourceProgramName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_program_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StudentAzureOid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_azure_oid");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("student_code");

                    b.Property<string>("StudentIdentity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_identity");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("student_name");

                    b.Property<string>("StudentNotes")
                        .HasColumnType("text")
                        .HasColumnName("student_notes");

                    b.Property<string>("TargetProgramCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_program_code");

                    b.Property<string>("TargetProgramName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target_program_name");

                    b.Property<int>("TotalCreditsHomologated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_credits_homologated");

                    b.Property<int>("TotalSubjectsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_subjects_approved");

                    b.Property<int>("TotalSubjectsEvaluated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_subjects_evaluated");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_homologation_requests_status");

                    b.HasIndex("StudentIdentity")
                        .HasDatabaseName("ix_homologation_requests_student_identity");

                    b.HasIndex("StudentIdentity", "SourceProgramCode", "TargetProgramCode", "Status")
                        .HasDatabaseName("ix_homologation_requests_active_check");

                    b.ToTable("homologation_requests", (string)null);
                });

            modelBuilder.Entity("Gradus.Domain.Entities.HomologationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByAzureOid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by_azure_oid");

                    b.Property<int>("MaxCreditsPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("max_credits_percentage");

                    b.Property<decimal>("MinGrade")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("min_grade");

                    b.Property<bool>("RequiresSameArea")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_same_area");

                    b.Property<string>("SourceProgramCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_program_code");

                    b.Property<string>("TargetProgramCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_program_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByAzureOid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("updated_by_azure_oid");

                    b.HasKey("Id");

                    b.HasIndex("Active")
                        .HasDatabaseName("ix_homologation_rules_active");

                    b.HasIndex("SourceProgramCode", "TargetProgramCode")
                        .IsUnique()
                        .HasDatabaseName("ix_homologation_rules_program_pair");

                    b.ToTable("homologation_rules", (string)null);
                });

            modelBuilder.Entity("Gradus.Domain.Entities.HomologationSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("auto_approved");

                    b.Property<string>("CoordinatorNotes")
                        .HasColumnType("text")
                        .HasColumnName("coordinator_notes");

                    b.Property<bool>("CoordinatorOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("coordinator_override");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HomologationRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("homologation_request_id");

                    b.Property<bool>("IsHomologable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_homologable");

                    b.Property<string>("OverriddenByAzureOid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("overridden_by_azure_oid");

                    b.Property<int?>("RejectionReason")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SourceArea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_area");

                    b.Property<int>("SourceCredits")
                        .HasColumnType("integer")
                        .HasColumnName("source_credits");

                    b.Property<decimal>("SourceGrade")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("source_grade");

                    b.Property<string>("SourceSubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_subject_code");

                    b.Property<string>("SourceSubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_subject_name");

                    b.Property<int>("TargetCredits")
                        .HasColumnType("integer")
                        .HasColumnName("target_credits");

                    b.Property<string>("TargetSubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_subject_code");

                    b.Property<string>("TargetSubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target_subject_name");

                    b.HasKey("Id");

                    b.HasIndex("HomologationRequestId")
                        .HasDatabaseName("ix_homologation_subjects_request_id");

                    b.HasIndex("IsHomologable")
                        .HasDatabaseName("ix_homologation_subjects_is_homologable");

                    b.ToTable("homologation_subjects", (string)null);
                });

            modelBuilder.Entity("Gradus.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("read_at");

                    b.Property<string>("RecipientAzureOid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recipient_azure_oid");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notifications_created_at");

                    b.HasIndex("RecipientAzureOid", "ReadAt")
                        .HasDatabaseName("ix_notifications_recipient_unread");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Gradus.Domain.Entities.SubjectEquivalence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByAzureOid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("created_by_azure_oid");

                    b.Property<Guid>("HomologationRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("homologation_rule_id");

                    b.Property<decimal?>("MinGradeOverride")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("min_grade_override");

                    b.Property<int>("SourceCredits")
                        .HasColumnType("integer")
                        .HasColumnName("source_credits");

                    b.Property<string>("SourceProgramCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_program_code");

                    b.Property<string>("SourceSubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_subject_code");

                    b.Property<string>("SourceSubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_subject_name");

                    b.Property<int>("TargetCredits")
                        .HasColumnType("integer")
                        .HasColumnName("target_credits");

                    b.Property<string>("TargetProgramCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_program_code");

                    b.Property<string>("TargetSubjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_subject_code");

                    b.Property<string>("TargetSubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("target_subject_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByAzureOid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("updated_by_azure_oid");

                    b.HasKey("Id");

                    b.HasIndex("HomologationRuleId");

                    b.HasIndex("SourceSubjectCode")
                        .HasDatabaseName("ix_subject_equivalences_source_subject");

                    b.HasIndex("SourceProgramCode", "TargetProgramCode")
                        .HasDatabaseName("ix_subject_equivalences_program_pair");

                    b.ToTable("subject_equivalences", (string)null);
                });

            modelBuilder.Entity("Gradus.Domain.Entities.HomologationSubject", b =>
                {
                    b.HasOne("Gradus.Domain.Entities.HomologationRequest", "HomologationRequest")
                        .WithMany("Subjects")
                        .HasForeignKey("HomologationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomologationRequest");
                });

            modelBuilder.Entity("Gradus.Domain.Entities.SubjectEquivalence", b =>
                {
                    b.HasOne("Gradus.Domain.Entities.HomologationRule", "HomologationRule")
                        .WithMany("SubjectEquivalences")
                        .HasForeignKey("HomologationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomologationRule");
                });

            modelBuilder.Entity("Gradus.Domain.Entities.HomologationRequest", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Gradus.Domain.Entities.HomologationRule", b =>
                {
                    b.Navigation("SubjectEquivalences");
                });
#pragma warning restore 612, 618
        }
    }
}
